Marg0n/Bicycle

- src/pages/home/Home.tsx
- src/pages/shared/Page404.tsx
Update: updated Page404 button and Home layout.
> Update: updated Page404 button and Home layout.

- index.html
- src/components/shared/ItemsCard.tsx
Add/Update: added icon on the title and added button on cards
> Add/Update: added icon on the title and added button on cards

- src/components/home/Hero.tsx
Fix: fixed redundant codes from Hero section
> Fix: fixed redundant codes from Hero section

- src/hooks/useAxiosSecure.tsx
Fix: fixed useAxiosSecure logout
> Fix: fixed useAxiosSecure logout

- .env
- src/pages/authentication/Login.tsx
- src/pages/authentication/register.tsx
- src/redux/api/baseApi.ts
- src/redux/features/auth/authApi.ts
- src/redux/features/auth/authSlice.ts
- src/routes/routes.tsx
Add: registration related file added. 
Fix: fixed routing issues.
> Add: registration related file added. Fix: fixed routing issues.

- src/App.tsx
- src/components/home/ResponsiveNavbar.tsx
- src/pages/authentication/Login.tsx
Add: added remember me, Auto-Login Using Stored Token, logout cleanup in home
> Add: added remember me, Auto-Login Using Stored Token, logout cleanup in home

- src/components/shared/Slider.tsx
- src/layout/AllBicycles/AllBicyclesLayout.tsx
Fix: fixed footer in AllBicyclesLayout and commented console.log in slider
> Fix: fixed footer in AllBicyclesLayout and commented console.log in slider

- src/components/shared/Footer.tsx
> Fix: footer fixed

- src/components/shared/ItemsCard.tsx
- src/components/shared/Slider.tsx
Fix: fixed unused var and slider type guard issue
> Fix: fixed unused var and slider type guard issue

- src/components/home/Hero.tsx
- src/components/shared/ItemsCard.tsx
Fix: fixed hero and card responsiveness
> Fix: fixed hero and card responsiveness

- src/components/home/ResponsiveNavbar.tsx
> Fix: fix in responsive navbar

- src/components/home/ResponsiveNavbar.tsx
> Fix: navbar active link

- src/components/home/ResponsiveNavbar.tsx
> Fix: navbar active type given

- src/components/shared/ItemsCard.tsx
- src/components/shared/Slider.tsx
- src/pages/home/FeaturedBicycles.tsx
Fix: fixed merged conflicts on ItemsCard, Slider, FeaturedBycicle
> Fix: fixed merged conflicts on ItemsCard, Slider, FeaturedBycicle

- src/pages/bicycleDetailes/bicyclesDetailes.tsx
Fix: design fixed for details page
> Fix: design fixed for details page

- src/components/home/Testimonial.tsx
> Fix: styles of testimonial

- src/pages/terms/PrivacyPolicy.tsx
> Fix: policy page

- src/components/shared/ItemsCard.tsx
- src/layout/checkout/CheckoutLayout.tsx
- src/pages/checkout/Checkout.tsx
- src/routes/routes.tsx
Some fixes on items card and checkout design & routing
> Some fixes on items card and checkout design & routing

- src/pages/checkout/Checkout.tsx
add: Re Added the mistakeenly previouse merged deletaed files from other branches of checkout
> add: Re Added the mistakeenly previouse merged deletaed files from other branches of checkout

- src/components/shared/CustomButton.tsx
Modify: modified custome button pointer
> Modify: modified custome button pointer

- src/components/shared/CustomButton.tsx
- src/pages/authentication/Login.tsx
- src/pages/authentication/register.tsx
custom button modified, login & register login type in button added
> custom button modified, login & register login type in button added

- src/layout/Dashboard/DashboardLayout.tsx
- src/pages/authentication/Login.tsx
- src/pages/authentication/register.tsx
Modify: login & register path cannot be accessed by user anymore
Add: DashboardLayout added
> Modify: login & register path cannot be accessed by user anymore & Add: DashboardLayout added

- src/components/home/ResponsiveNavbar.tsx
- src/layout/Dashboard/DashboardLayout.tsx
- src/routes/routes.tsx
Add/Fix: re modified layout for dashboard + routes
> Add/Fix: re modified layout for dashboard + routes

- src/routes/routes.tsx
- src/routes/user.routes.tsx
Modify: modified dashboard routes
> Modify: modified dashboard routes

- src/components/home/ResponsiveNavbar.tsx
Modify: modified navbar logo click destination based on loin state
> Modify: modified navbar logo click destination based on loin state

- src/routes/admin.routes.tsx
- src/routes/user.routes.tsx
- src/utils/sidebarItemsGenerator.tsx
Fix: fixed the route issue of admin & customer
> Fix: fixed the route issue of admin & customer

- src/pages/dashboard/admin/products/AddBicycle.tsx
- src/redux/api/baseApi.ts
Add: AddBicycle function added & slightly changed baseApi
> Add: AddBicycle function added & slightly changed baseApi

- src/pages/dashboard/admin/products/AddBicycle.tsx
Modify: AddBicycle function changed
> Modify: AddBicycle function changed

- src/components/shared/ItemsCard.tsx
Modify: ItemsCard modified to deduct description
> Modify: ItemsCard modified to deduct description

- src/pages/allBicycles/AllBicycles.tsx
Modify: AllBicycles page  limit
> Modify: AllBicycles page  limit

- src/components/shared/Slider.tsx
- src/pages/home/FeaturedBicycles.tsx
Modify: Slider & Featured  section now is sorted to 6
> Modify: Slider & Featured  section now is sorted to 6

- package-lock.json
- package.json
- src/pages/dashboard/admin/userManage/userManagement.tsx
Fix: toast are imported from sonner to be in consistence
> Fix: toast are imported from sonner to be in consistence

- src/pages/dashboard/admin/userManage/userManagement.tsx
Fix: userManagement any type resolved
> Fix: userManagement any type resolved

- src/pages/dashboard/admin/products/AllProductsPage.tsx
- src/pages/dashboard/admin/userManage/userManagement.tsx
> Modify: userManagement style

- src/hooks/useAxiosCommon.tsx
- src/pages/checkout/Checkout.tsx
- src/pages/dashboard/admin/orders/ManageOrders.tsx
- src/pages/failedOrder/FailedOrder.tsx
- src/pages/successOrder/SuccessOrder.tsx
- src/redux/api/orderApi.ts
- src/routes/routes.tsx
- src/utils/types.ts
> i am done here

- src/components/shared/Slider.tsx
- src/pages/checkout/Checkout.tsx
- src/pages/home/FeaturedBicycles.tsx
Fix: fixed !inStock bicycles will not be shown in slider & features and will not navigate to checkoutpage
> Fix: fixed !inStock bicycles will not be shown in slider & features and will not navigate to checkoutpage

- src/components/home/Testimonial.tsx
- src/pages/about/About.tsx
- src/pages/checkout/Checkout.tsx
- src/pages/dashboard/admin/orders/ManageOrders.tsx
- src/utils/types.ts
Modify: modified testimonial & About
Modify: modified OrderedItem. Fix: fixed checkout and Manageorders
> Modify: modified testimonial & About, modified OrderedItem. Fix: fixed checkout and Manageorders

- src/routes/ScrollToTop.tsx
> Modify: modified ScrollToTop

- src/components/shared/ItemsCard.tsx
- src/layout/Dashboard/DashboardLayout.tsx
- src/pages/dashboard/customer/orders/viewOrders.tsx
- src/redux/api/orderApi.ts
- src/redux/api/productApi.ts
- src/redux/features/order/orderslice.ts
> Fix: fixed build problems

- src/pages/authentication/register.tsx
- src/pages/checkout/Checkout.tsx
- src/pages/dashboard/admin/orders/ManageOrders.tsx
- src/pages/dashboard/admin/userManage/userManagement.tsx
- src/pages/dashboard/customer/orders/viewOrders.tsx
> Fix: commited console

- src/components/home/Testimonial.tsx
> Add: new testimonial added

- src/components/home/Testimonial.tsx
- src/components/shared/Footer.tsx
Fix/Add/Modify: fixed footer & testimonial
> Fix/Add/Modify: fixed footer & testimonial
